package com.example.androidgame.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table artical
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table artical
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table artical
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public ArticalExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table artical
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArticalIdIsNull() {
            addCriterion("artical_id is null");
            return (Criteria) this;
        }

        public Criteria andArticalIdIsNotNull() {
            addCriterion("artical_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticalIdEqualTo(Integer value) {
            addCriterion("artical_id =", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotEqualTo(Integer value) {
            addCriterion("artical_id <>", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdGreaterThan(Integer value) {
            addCriterion("artical_id >", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("artical_id >=", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdLessThan(Integer value) {
            addCriterion("artical_id <", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdLessThanOrEqualTo(Integer value) {
            addCriterion("artical_id <=", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdIn(List<Integer> values) {
            addCriterion("artical_id in", values, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotIn(List<Integer> values) {
            addCriterion("artical_id not in", values, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdBetween(Integer value1, Integer value2) {
            addCriterion("artical_id between", value1, value2, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("artical_id not between", value1, value2, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalNameIsNull() {
            addCriterion("artical_name is null");
            return (Criteria) this;
        }

        public Criteria andArticalNameIsNotNull() {
            addCriterion("artical_name is not null");
            return (Criteria) this;
        }

        public Criteria andArticalNameEqualTo(String value) {
            addCriterion("artical_name =", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameNotEqualTo(String value) {
            addCriterion("artical_name <>", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameGreaterThan(String value) {
            addCriterion("artical_name >", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameGreaterThanOrEqualTo(String value) {
            addCriterion("artical_name >=", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameLessThan(String value) {
            addCriterion("artical_name <", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameLessThanOrEqualTo(String value) {
            addCriterion("artical_name <=", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameLike(String value) {
            addCriterion("artical_name like", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameNotLike(String value) {
            addCriterion("artical_name not like", value, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameIn(List<String> values) {
            addCriterion("artical_name in", values, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameNotIn(List<String> values) {
            addCriterion("artical_name not in", values, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameBetween(String value1, String value2) {
            addCriterion("artical_name between", value1, value2, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalNameNotBetween(String value1, String value2) {
            addCriterion("artical_name not between", value1, value2, "articalName");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceIsNull() {
            addCriterion("artical_introduce is null");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceIsNotNull() {
            addCriterion("artical_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceEqualTo(String value) {
            addCriterion("artical_introduce =", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceNotEqualTo(String value) {
            addCriterion("artical_introduce <>", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceGreaterThan(String value) {
            addCriterion("artical_introduce >", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("artical_introduce >=", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceLessThan(String value) {
            addCriterion("artical_introduce <", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceLessThanOrEqualTo(String value) {
            addCriterion("artical_introduce <=", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceLike(String value) {
            addCriterion("artical_introduce like", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceNotLike(String value) {
            addCriterion("artical_introduce not like", value, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceIn(List<String> values) {
            addCriterion("artical_introduce in", values, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceNotIn(List<String> values) {
            addCriterion("artical_introduce not in", values, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceBetween(String value1, String value2) {
            addCriterion("artical_introduce between", value1, value2, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalIntroduceNotBetween(String value1, String value2) {
            addCriterion("artical_introduce not between", value1, value2, "articalIntroduce");
            return (Criteria) this;
        }

        public Criteria andArticalDetailIsNull() {
            addCriterion("artical_detail is null");
            return (Criteria) this;
        }

        public Criteria andArticalDetailIsNotNull() {
            addCriterion("artical_detail is not null");
            return (Criteria) this;
        }

        public Criteria andArticalDetailEqualTo(String value) {
            addCriterion("artical_detail =", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailNotEqualTo(String value) {
            addCriterion("artical_detail <>", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailGreaterThan(String value) {
            addCriterion("artical_detail >", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailGreaterThanOrEqualTo(String value) {
            addCriterion("artical_detail >=", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailLessThan(String value) {
            addCriterion("artical_detail <", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailLessThanOrEqualTo(String value) {
            addCriterion("artical_detail <=", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailLike(String value) {
            addCriterion("artical_detail like", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailNotLike(String value) {
            addCriterion("artical_detail not like", value, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailIn(List<String> values) {
            addCriterion("artical_detail in", values, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailNotIn(List<String> values) {
            addCriterion("artical_detail not in", values, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailBetween(String value1, String value2) {
            addCriterion("artical_detail between", value1, value2, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDetailNotBetween(String value1, String value2) {
            addCriterion("artical_detail not between", value1, value2, "articalDetail");
            return (Criteria) this;
        }

        public Criteria andArticalDateIsNull() {
            addCriterion("artical_date is null");
            return (Criteria) this;
        }

        public Criteria andArticalDateIsNotNull() {
            addCriterion("artical_date is not null");
            return (Criteria) this;
        }

        public Criteria andArticalDateEqualTo(Date value) {
            addCriterion("artical_date =", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateNotEqualTo(Date value) {
            addCriterion("artical_date <>", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateGreaterThan(Date value) {
            addCriterion("artical_date >", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateGreaterThanOrEqualTo(Date value) {
            addCriterion("artical_date >=", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateLessThan(Date value) {
            addCriterion("artical_date <", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateLessThanOrEqualTo(Date value) {
            addCriterion("artical_date <=", value, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateIn(List<Date> values) {
            addCriterion("artical_date in", values, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateNotIn(List<Date> values) {
            addCriterion("artical_date not in", values, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateBetween(Date value1, Date value2) {
            addCriterion("artical_date between", value1, value2, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalDateNotBetween(Date value1, Date value2) {
            addCriterion("artical_date not between", value1, value2, "articalDate");
            return (Criteria) this;
        }

        public Criteria andArticalImageIsNull() {
            addCriterion("artical_image is null");
            return (Criteria) this;
        }

        public Criteria andArticalImageIsNotNull() {
            addCriterion("artical_image is not null");
            return (Criteria) this;
        }

        public Criteria andArticalImageEqualTo(String value) {
            addCriterion("artical_image =", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageNotEqualTo(String value) {
            addCriterion("artical_image <>", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageGreaterThan(String value) {
            addCriterion("artical_image >", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageGreaterThanOrEqualTo(String value) {
            addCriterion("artical_image >=", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageLessThan(String value) {
            addCriterion("artical_image <", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageLessThanOrEqualTo(String value) {
            addCriterion("artical_image <=", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageLike(String value) {
            addCriterion("artical_image like", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageNotLike(String value) {
            addCriterion("artical_image not like", value, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageIn(List<String> values) {
            addCriterion("artical_image in", values, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageNotIn(List<String> values) {
            addCriterion("artical_image not in", values, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageBetween(String value1, String value2) {
            addCriterion("artical_image between", value1, value2, "articalImage");
            return (Criteria) this;
        }

        public Criteria andArticalImageNotBetween(String value1, String value2) {
            addCriterion("artical_image not between", value1, value2, "articalImage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table artical
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table artical
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}