package com.example.androidgame.entity;

import java.util.ArrayList;
import java.util.List;

public class DiscussExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table discuss
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public DiscussExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDiscussIdIsNull() {
            addCriterion("discuss_id is null");
            return (Criteria) this;
        }

        public Criteria andDiscussIdIsNotNull() {
            addCriterion("discuss_id is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussIdEqualTo(Integer value) {
            addCriterion("discuss_id =", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdNotEqualTo(Integer value) {
            addCriterion("discuss_id <>", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdGreaterThan(Integer value) {
            addCriterion("discuss_id >", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("discuss_id >=", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdLessThan(Integer value) {
            addCriterion("discuss_id <", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdLessThanOrEqualTo(Integer value) {
            addCriterion("discuss_id <=", value, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdIn(List<Integer> values) {
            addCriterion("discuss_id in", values, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdNotIn(List<Integer> values) {
            addCriterion("discuss_id not in", values, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdBetween(Integer value1, Integer value2) {
            addCriterion("discuss_id between", value1, value2, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussIdNotBetween(Integer value1, Integer value2) {
            addCriterion("discuss_id not between", value1, value2, "discussId");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleIsNull() {
            addCriterion("discuss_title is null");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleIsNotNull() {
            addCriterion("discuss_title is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleEqualTo(String value) {
            addCriterion("discuss_title =", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleNotEqualTo(String value) {
            addCriterion("discuss_title <>", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleGreaterThan(String value) {
            addCriterion("discuss_title >", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleGreaterThanOrEqualTo(String value) {
            addCriterion("discuss_title >=", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleLessThan(String value) {
            addCriterion("discuss_title <", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleLessThanOrEqualTo(String value) {
            addCriterion("discuss_title <=", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleLike(String value) {
            addCriterion("discuss_title like", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleNotLike(String value) {
            addCriterion("discuss_title not like", value, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleIn(List<String> values) {
            addCriterion("discuss_title in", values, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleNotIn(List<String> values) {
            addCriterion("discuss_title not in", values, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleBetween(String value1, String value2) {
            addCriterion("discuss_title between", value1, value2, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussTitleNotBetween(String value1, String value2) {
            addCriterion("discuss_title not between", value1, value2, "discussTitle");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailIsNull() {
            addCriterion("discuss_detail is null");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailIsNotNull() {
            addCriterion("discuss_detail is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailEqualTo(String value) {
            addCriterion("discuss_detail =", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailNotEqualTo(String value) {
            addCriterion("discuss_detail <>", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailGreaterThan(String value) {
            addCriterion("discuss_detail >", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailGreaterThanOrEqualTo(String value) {
            addCriterion("discuss_detail >=", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailLessThan(String value) {
            addCriterion("discuss_detail <", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailLessThanOrEqualTo(String value) {
            addCriterion("discuss_detail <=", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailLike(String value) {
            addCriterion("discuss_detail like", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailNotLike(String value) {
            addCriterion("discuss_detail not like", value, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailIn(List<String> values) {
            addCriterion("discuss_detail in", values, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailNotIn(List<String> values) {
            addCriterion("discuss_detail not in", values, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailBetween(String value1, String value2) {
            addCriterion("discuss_detail between", value1, value2, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussDetailNotBetween(String value1, String value2) {
            addCriterion("discuss_detail not between", value1, value2, "discussDetail");
            return (Criteria) this;
        }

        public Criteria andDiscussImageIsNull() {
            addCriterion("discuss_image is null");
            return (Criteria) this;
        }

        public Criteria andDiscussImageIsNotNull() {
            addCriterion("discuss_image is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussImageEqualTo(String value) {
            addCriterion("discuss_image =", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageNotEqualTo(String value) {
            addCriterion("discuss_image <>", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageGreaterThan(String value) {
            addCriterion("discuss_image >", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageGreaterThanOrEqualTo(String value) {
            addCriterion("discuss_image >=", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageLessThan(String value) {
            addCriterion("discuss_image <", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageLessThanOrEqualTo(String value) {
            addCriterion("discuss_image <=", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageLike(String value) {
            addCriterion("discuss_image like", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageNotLike(String value) {
            addCriterion("discuss_image not like", value, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageIn(List<String> values) {
            addCriterion("discuss_image in", values, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageNotIn(List<String> values) {
            addCriterion("discuss_image not in", values, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageBetween(String value1, String value2) {
            addCriterion("discuss_image between", value1, value2, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussImageNotBetween(String value1, String value2) {
            addCriterion("discuss_image not between", value1, value2, "discussImage");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeIsNull() {
            addCriterion("discuss_type is null");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeIsNotNull() {
            addCriterion("discuss_type is not null");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeEqualTo(String value) {
            addCriterion("discuss_type =", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeNotEqualTo(String value) {
            addCriterion("discuss_type <>", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeGreaterThan(String value) {
            addCriterion("discuss_type >", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeGreaterThanOrEqualTo(String value) {
            addCriterion("discuss_type >=", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeLessThan(String value) {
            addCriterion("discuss_type <", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeLessThanOrEqualTo(String value) {
            addCriterion("discuss_type <=", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeLike(String value) {
            addCriterion("discuss_type like", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeNotLike(String value) {
            addCriterion("discuss_type not like", value, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeIn(List<String> values) {
            addCriterion("discuss_type in", values, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeNotIn(List<String> values) {
            addCriterion("discuss_type not in", values, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeBetween(String value1, String value2) {
            addCriterion("discuss_type between", value1, value2, "discussType");
            return (Criteria) this;
        }

        public Criteria andDiscussTypeNotBetween(String value1, String value2) {
            addCriterion("discuss_type not between", value1, value2, "discussType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table discuss
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}