package com.example.androidgame.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserarticalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userartical
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userartical
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userartical
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public UserarticalExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userartical
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserarticalIdIsNull() {
            addCriterion("userartical_id is null");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdIsNotNull() {
            addCriterion("userartical_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdEqualTo(Integer value) {
            addCriterion("userartical_id =", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdNotEqualTo(Integer value) {
            addCriterion("userartical_id <>", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdGreaterThan(Integer value) {
            addCriterion("userartical_id >", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userartical_id >=", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdLessThan(Integer value) {
            addCriterion("userartical_id <", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdLessThanOrEqualTo(Integer value) {
            addCriterion("userartical_id <=", value, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdIn(List<Integer> values) {
            addCriterion("userartical_id in", values, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdNotIn(List<Integer> values) {
            addCriterion("userartical_id not in", values, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdBetween(Integer value1, Integer value2) {
            addCriterion("userartical_id between", value1, value2, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserarticalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userartical_id not between", value1, value2, "userarticalId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andArticalIdIsNull() {
            addCriterion("artical_id is null");
            return (Criteria) this;
        }

        public Criteria andArticalIdIsNotNull() {
            addCriterion("artical_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticalIdEqualTo(Integer value) {
            addCriterion("artical_id =", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotEqualTo(Integer value) {
            addCriterion("artical_id <>", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdGreaterThan(Integer value) {
            addCriterion("artical_id >", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("artical_id >=", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdLessThan(Integer value) {
            addCriterion("artical_id <", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdLessThanOrEqualTo(Integer value) {
            addCriterion("artical_id <=", value, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdIn(List<Integer> values) {
            addCriterion("artical_id in", values, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotIn(List<Integer> values) {
            addCriterion("artical_id not in", values, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdBetween(Integer value1, Integer value2) {
            addCriterion("artical_id between", value1, value2, "articalId");
            return (Criteria) this;
        }

        public Criteria andArticalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("artical_id not between", value1, value2, "articalId");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNull() {
            addCriterion("game_id is null");
            return (Criteria) this;
        }

        public Criteria andGameIdIsNotNull() {
            addCriterion("game_id is not null");
            return (Criteria) this;
        }

        public Criteria andGameIdEqualTo(Integer value) {
            addCriterion("game_id =", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotEqualTo(Integer value) {
            addCriterion("game_id <>", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThan(Integer value) {
            addCriterion("game_id >", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_id >=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThan(Integer value) {
            addCriterion("game_id <", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdLessThanOrEqualTo(Integer value) {
            addCriterion("game_id <=", value, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdIn(List<Integer> values) {
            addCriterion("game_id in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotIn(List<Integer> values) {
            addCriterion("game_id not in", values, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdBetween(Integer value1, Integer value2) {
            addCriterion("game_id between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andGameIdNotBetween(Integer value1, Integer value2) {
            addCriterion("game_id not between", value1, value2, "gameId");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateIsNull() {
            addCriterion("userartical_date is null");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateIsNotNull() {
            addCriterion("userartical_date is not null");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateEqualTo(Date value) {
            addCriterion("userartical_date =", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateNotEqualTo(Date value) {
            addCriterion("userartical_date <>", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateGreaterThan(Date value) {
            addCriterion("userartical_date >", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateGreaterThanOrEqualTo(Date value) {
            addCriterion("userartical_date >=", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateLessThan(Date value) {
            addCriterion("userartical_date <", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateLessThanOrEqualTo(Date value) {
            addCriterion("userartical_date <=", value, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateIn(List<Date> values) {
            addCriterion("userartical_date in", values, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateNotIn(List<Date> values) {
            addCriterion("userartical_date not in", values, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateBetween(Date value1, Date value2) {
            addCriterion("userartical_date between", value1, value2, "userarticalDate");
            return (Criteria) this;
        }

        public Criteria andUserarticalDateNotBetween(Date value1, Date value2) {
            addCriterion("userartical_date not between", value1, value2, "userarticalDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userartical
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userartical
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}