file:
  uploadFolder: D://upload/
  staticAccessPath: /uploadImage/**
server:
  port: 443
  tomcat:
    uri-encoding: UTF-8



spring:
  datasource:
    url: jdbc:mysql://120.26.74.186:3306/Android?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false


    username: root
    password: 009858jk
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
  mvc:
    static-path-pattern: /**







mybatis:
  mapper-locations: classpath:com/example/dao/*.xml


