package com.example.androidgame.mapper;

import com.example.androidgame.entity.Userartical;
import com.example.androidgame.entity.UserarticalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserarticalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    long countByExample(UserarticalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int deleteByExample(UserarticalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userarticalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int insert(Userartical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int insertSelective(Userartical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    List<Userartical> selectByExample(UserarticalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    Userartical selectByPrimaryKey(Integer userarticalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userartical record, @Param("example") UserarticalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userartical record, @Param("example") UserarticalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userartical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userartical
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userartical record);
}