package com.example.androidgame.mapper;

import com.example.androidgame.entity.Userdiscuss;

import java.util.List;

import com.example.androidgame.entity.UserdiscussExample;
import org.apache.ibatis.annotations.Param;

public interface UserdiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    long countByExample(UserdiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int deleteByExample(UserdiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userdiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int insert(Userdiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int insertSelective(Userdiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    List<Userdiscuss> selectByExample(UserdiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    Userdiscuss selectByPrimaryKey(Integer userdiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userdiscuss record, @Param("example") UserdiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userdiscuss record, @Param("example") UserdiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userdiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdiscuss
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userdiscuss record);
}