package com.example.androidgame.mapper;

import com.example.androidgame.entity.Userall;
import com.example.androidgame.entity.UserallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    long countByExample(UserallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int deleteByExample(UserallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int insert(Userall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int insertSelective(Userall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    List<Userall> selectByExample(UserallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    Userall selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userall record, @Param("example") UserallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userall record, @Param("example") UserallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userall
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userall record);

    List<Userall> selectAll();

    Userall selectUserByArtical(int articalId);

    Userall selectUserByGame(int gameId);
}